version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: nullPointers-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nullPointersDatabase
    ports:
      - "3306:3306"
